[project]
name = "dotfiles"
version = "0.1.0"
description = "My personal dotfiles. Simply simlinks the config files to the home directory."
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "mypy>=1.19.0",
    "ruff>=0.14.9",
]
